### ISSUE TITLE
about the sh scripts 

### ISSUE THREAD

**Issue by DJMeng** [snap-stanford/bc-emb#1]
Thank you for your work, could you please add the scripts , such as download.sh...

**Comment by weihua916** [comment]
Apologies. Just added the script. See [here](https://github.com/snap-stanford/bc-emb/blob/main/dataset_preprocessing/amazon/download.sh).

**Comment by DJMeng** [comment]
> Apologies. Just added the script. See [here](https://github.com/snap-stanford/bc-emb/blob/main/dataset_preprocessing/amazon/download.sh).

Thanks bro.
